# Generated by Django 4.0.5 on 2022-07-07 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fairbet_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Betting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='placedAmount')),
                ('bet_on_team', models.CharField(max_length=100, null=True, verbose_name='betOnTeam')),
                ('status', models.CharField(choices=[('B', 'BACK'), ('L', 'LAY')], max_length=100, verbose_name='Status')),
                ('odds', models.FloatField(null=True, verbose_name='Odds')),
                ('winning_team', models.CharField(blank=True, default='Not declared yet', max_length=100, null=True, verbose_name='winningTeam')),
                ('loss_profit', models.FloatField(default=0.0, null=True, verbose_name='lossProfit')),
                ('match', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='liveMatch')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fairbet_auth_app.profile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
