# Generated by Django 4.0.5 on 2022-06-30 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fairbet_auth_app', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Betting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='placedAmount')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fairbet_auth_app.profile')),
            ],
        ),
    ]
