# Generated by Django 4.0.5 on 2022-06-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_placed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='betting',
            name='bet_on_team',
            field=models.CharField(max_length=100, null=True, verbose_name='betOnTeam'),
        ),
        migrations.AddField(
            model_name='betting',
            name='loss_profilt',
            field=models.FloatField(null=True, verbose_name='lossProfit'),
        ),
        migrations.AddField(
            model_name='betting',
            name='odds',
            field=models.FloatField(null=True, verbose_name='Odds'),
        ),
        migrations.AddField(
            model_name='betting',
            name='winning_team',
            field=models.CharField(max_length=100, null=True, verbose_name='winningTeam'),
        ),
        migrations.AlterField(
            model_name='betting',
            name='status',
            field=models.CharField(choices=[('B', 'BACK'), ('L', 'LAY')], max_length=100, verbose_name='Status'),
        ),
    ]
