# Generated by Django 4.0.5 on 2022-07-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_placed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='betting',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='isClosed'),
        ),
    ]
