# Generated by Django 4.0.5 on 2022-06-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_placed', '0002_betting_bet_on_team_betting_loss_profilt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='betting',
            old_name='loss_profilt',
            new_name='loss_profit',
        ),
    ]
