# Generated by Django 4.0.5 on 2022-07-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_placed', '0003_rename_loss_profilt_betting_loss_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betting',
            name='loss_profit',
            field=models.FloatField(default=0.0, null=True, verbose_name='lossProfit'),
        ),
        migrations.AlterField(
            model_name='betting',
            name='winning_team',
            field=models.CharField(blank=True, default='Not declared yet', max_length=100, null=True, verbose_name='winningTeam'),
        ),
    ]
