# Generated by Django 4.0.5 on 2022-07-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_placed', '0004_alter_betting_loss_profit_alter_betting_winning_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='betting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='betting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
