# Generated by Django 4.0.5 on 2022-07-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_placed', '0005_betting_created_at_betting_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='betting',
            name='match',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='liveMatch'),
        ),
    ]
