# Generated by Django 4.0.5 on 2022-07-06 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_placed', '0006_betting_match'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='betting',
            options={'ordering': ['created_at']},
        ),
    ]
