# Generated by Django 4.0.5 on 2022-07-06 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_transaction_status_wallet_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['created']},
        ),
    ]
