# Generated by Django 4.0.5 on 2022-06-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairbet_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
